name 'geniisuat'
description 'Creates Sitecore instances in AWS for QA and Production environments.'
license 'all_rights'
long_description 'This cookbook will contain configuration necessary for a Sitecore developer to build out a functioning Sitecore environment in Amazon EC2.'
maintainer 'Louis Corbo'
maintainer_email 'lcorbo@singlestoneconsulting.com'
version '0.1.0'

depends 'windows'
depends 'windows_feature'
depends 'powershell'